[package]
name = "calendar-as-diary"
version = "0.1.0"
authors = ["owen8877 <owentoget@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
